### ISSUE TITLE
Async generators

### ISSUE THREAD

**Issue by fkling** [facebook/regenerator#163]
What are the plans about supporting [async generators](https://github.com/jhusain/asyncgenerator)? Too early?

**Comment by sebmck** [comment]
They're already supported.

**Comment by Dashed** [comment]
I didn't realize this until I browsed the commit history. This should be mentioned in the `README` or somewhere.

**Comment by fkling** [comment]
@sebmck: The current implementation seems to simply return a promise and never resolves it:

```
async function *range() {
  yield 1;
  yield 2;
}
console.log(range());
```

returns

```
Promise {done: function, [[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
```

How can I consume it?

According to the proposal, an *Observable* should be returned.

**Comment by benjamn** [comment]
The current implementation of Regenerator allows a function to be either `async` or a `GeneratorFunction`, but not both. What @jhusain is suggesting is a function that can contain both `await` and `yield`, with distinct meanings.

As you may already know, the current implementation simply translates `await` to `yield`, so the distinction between the two would be lost if we tried to use `yield` in an `async` function.

There shouldn't be anything terribly tricky about supporting both `await` and `yield` in the same function. Maybe the simplest thing to do would be to translate `await x` into `yield regeneratorRuntime.wrapAwaitArgument(x)` and then modify the `regeneratorRuntime.async` wrapper to differentiate between wrapped and unwrapped values. Whenever an `async` function is also a generator, `regeneratorRuntime.async` would return an `Observable` instead of a `Promise`, and the values generated by the `Observable` would be any unwrapped values that were `yield`ed.

On the one hand, Regenerator is a good place to try out new language features like this. On the other hand, we're still a long way away from a stable spec for `async` `GeneratorFunction`s. I'm sure we'll end up supporting this, but I want to make sure we support `async` functions as well as possible in the meantime.

**Comment by fkling** [comment]
Thanks for the insight, I appreciate the explanation! I know the proposal is in an early state, that's why I was mostly interested in your thoughts about it (wrt regenerator).

>  I'm sure we'll end up supporting this, but I want to make sure we support async functions as well as possible in the meantime.

What do you mean by that? Would supporting async generators impact the support of "normal" async functions?

**Comment by benjamingr** [comment]
Note that this would also require a `for... on` loop to be added to the consuming side. I'd definitely be interested in seeing this.

**Comment by donaldpipowitch** [comment]
Really looking forward to async generators which are super useful for using streams with async/await. I like the https://github.com/jhusain/asyncgenerator proposal which seems to add a native `Observable` object, so you can compose two observables and do things like `Observable.fromEvent` or `Observable.prototype.concatMap`. I hope this spec gains more interest soon and would love to see this as an experimental feature.

**Comment by domenic** [comment]
The alternate async generator proposal at https://github.com/zenparsing/async-iteration/ would be more useful for streams as it supports backpressure. It also matches better with generator/iterator semantics instead of introducing observables as a new semantic.

**Comment by donaldpipowitch** [comment]
Can these be composed, too? (Merging two Observables into a new one, etc.) If yes, I than this is probably the better spec.

**Comment by domenic** [comment]
Of course.

**Comment by donaldpipowitch** [comment]
:dancer: :heart:

**Comment by benjamn** [comment]
Are there any good polyfills for `Observable`? Asking without investigating—sorry if I'm missing the obvious!

**Comment by benjamingr** [comment]
@jhusain ping ^

**Comment by jhusain** [comment]
@zenparsing has a nominal type polyfill here:

https://github.com/zenparsing/es-observable/blob/master/src/Observable.js

**Comment by benjamingr** [comment]
This can be closed as the proposal is being withdrawn

**Comment by benjamn** [comment]
Looks like `async function*`s are moving towards returning [AsyncIterator](https://github.com/zenparsing/async-iteration/#the-asynciterator-interface)s instead.

**Comment by benjamingr** [comment]
Awesome, thanks.

**Comment by zenparsing** [comment]
@benjamn I've updated the proposal for async for-of:

```js
async function f() {
    for await (let x of y) {
        // Stuff
    }
}
```

(There are issues on the repo for discussing bikeshedding if you have any input.)

It seems like this is something that would need to be compiled with regenerator, as opposed to babel (since it involves awaiting the iteration result).  Is that right?

**Comment by benjamn** [comment]
@zenparsing commented there: https://github.com/zenparsing/async-iteration/issues/11#issuecomment-124737820
