### ISSUE TITLE
Errors in async functions get swallowed

### ISSUE THREAD

**Issue by brooklynDev** [facebook/regenerator#175]
The following code does not transform as expected:
```js
async function foo(){
	throw new Error();
}

try{
  foo();
}
catch(e){
	console.log('I NEVER GET CALLED');
}

```

In the above code, since the async function is throwing an exception, I'd expect the catch block to run when calling the `foo` function, however it never gets called.

**Comment by benjamn** [comment]
In this example, the error becomes the rejection reason for the `Promise` returned by the `async` function, so you'll want to catch it using the `Promise#catch` method:
```js
foo().catch(function(e) { ... })
```
which is similar to calling `.then` with both a success callback and an error callback:
```js
foo().then(function(result) { ... }, function(error) { ... });
```
Now, you could argue that the `Promise` is swallowing the error, but at least it guarantees the error is preserved somewhere (you just have to remember to examine it).

**Comment by bolinfest** [comment]
At least in Atom (which is based on Chrome), these are considered
"unhandled Promises," and they get displayed in the console, which is
exceptionally helpful.

**Comment by mpj** [comment]
I love promises and streams, but this is a thing that disturbs me a lot. I think this is a really, really bad development experience. It's all well and good in the happy-path, but extremely confusing when you make a typo inside an async function during development, and NOTHING happens. Instead of simply giving you an error, you now have to start hunting for where your promise chain is broken.

**Comment by petkaantonov** [comment]
`foo` is an async function, you need to `await` it to transform it to a direct return value/thrown exception:

```js
async function foo(){
    throw new Error();
}

async function bar() {
    try {
        await foo();
    } catch (e) {
        console.log('I should get called');
    }
}
```

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by marudor** [comment]
Problem is this line
https://github.com/facebook/regenerator/blob/18b944c8ec91454192a5f09f543a9f2c98e4bbce/runtime.js#L192
It executes the catch method on the promise once.
That way the usual "maybe unhandled promise rejection" from libraries does not work.
As the regenerator runtime actively swallows all exceptions thrown by the Promise.

I would REALLY appreciate if you could change this. Swalloing every Exception makes debugging way harder.

**Comment by benjamn** [comment]
@marudor thank you for bringing that to my attention! If I can fix that problem, then I think this issue can be closed, since `Promise` implementations will be able to track unhandled rejections however they see fit, without interference from Regenerator.

Specifically, attaching that `catch` handler is important for keeping `AsyncIterator` iterations safe from the errors of previous iterations, but simple `async` functions (which are implemented as single-iteration `AsyncIterator`s) never need to worry about more than one iteration, so the `catch` handler never needs to be attached. Fix coming momentarily.

**Comment by benjamn** [comment]
Published [v0.8.39](https://github.com/facebook/regenerator/releases/tag/v0.8.39) to NPM.

Verified that unhandled `Promise` rejections are now printed to the console in Chrome. Try running the following code [here](http://facebook.github.io/regenerator/) to see for yourself:
```js
async function test() {
  throw new Error("test");
}
test();
```

**Comment by benjamn** [comment]
Babel pull request: https://github.com/babel/babel/pull/2414

**Comment by benjamn** [comment]
I have to say I'm pretty excited about this resolution, because I didn't think there was anything I could do to help with this problem, and I was wrong about that!

**Comment by marudor** [comment]
Glad I could help. Took me quite a while to find this little bugger.
