### ISSUE TITLE
Extract a regenerator-core NPM package that provides only the transform function

### ISSUE THREAD

**Issue by benjamn** [facebook/regenerator#191]
The proposed `regenerator-core` package would not do any parsing or printing, and would not depend on [esprima-fb](https://www.npmjs.com/package/esprima-fb) or [recast](https://github.com/benjamn/recast) (or any specific parser or printer, for that matter).

For traversal purposes, the `regenerator-core` package would still depend on https://github.com/benjamn/ast-types, of course.

The official [regenerator package](https://github.com/facebook/regenerator) would then depend on `regenerator-core`.

Presumably @sebmck will want to make https://github.com/babel/babel depend directly on `regenerator-core` (per https://github.com/babel/babel/issues/1123).

**Comment by sebmck** [comment]
Any update on this? Would be awesome to have since right now `esprima` and `recast` are being unnecessarily `require`d.

**Comment by benjamn** [comment]
I'll get to it, it's just not my highest priority right now.

In the meantime, is there a way for Regenerator to depend on the Babel Acorn parser without pulling in all of Babel?

**Comment by sebmck** [comment]
> I'll get to it, it's just not my highest priority right now.

All good, not a huge priority for me either.

> In the meantime, is there a way for Regenerator to depend on the Babel Acorn parser without pulling in all of Babel?

Kinda, but it's hacky. `require("babel-core/lib/acorn")`. The status of the Babel Acorn fork is kinda wonky (it always has been). There's likely no way all the changes would get merged into upstream Acorn but I'm hesitant to fork it further. Need to reevaluate it since facebook/esprima#111 deprecated `esprima-fb` even though I've actively discouraged use of the internal parser so a complete divergence might be necessary, unsure.

**Comment by fkling** [comment]
@sebmck: Being able to just include the parser would be very useful for sure.

> I've actively discouraged use of the internal parser 

I think that ship has sailed. Babel is pretty popular now. Any tool that wants to be able to consume code that is written with Babel in mind would need access to that parser.

Or we have to find a way to have all the customizations as Acorn plugins. I know this was talked about before, not sure what the current state is.

**Comment by sebmck** [comment]
@fkling 

> I think that ship has sailed. Babel is pretty popular now.

I know but I have to maintain it still. I don't have enough time to work on Babel as it is so I don't really want to add more to that, that _might_ change in the near future, which is why it's in limbo for the time being.

> Or we have to find a way to have all the customizations as Acorn plugins. I know this was talked about before, not sure what the current state is.

Acorn plugins are way too unstable at this point as they just rely on method overloading, although I'm not sure there's any better way.

**Comment by impinball** [comment]
BTW, @sebmck uses `regenerator/runtime` only for Babel output (except for the obvious case of code making use of Regenerator's transpiler API itself). Although [a package exists for that use case](https://npm.im/regenerator-runtime-only). And that kind of thing is what I feel is more important.

**Comment by benjamn** [comment]
This has been fixed by #259. Specifically [`regenerator-transform`](https://github.com/facebook/regenerator/tree/master/packages/regenerator-transform) is now published independently.
