### ISSUE TITLE
Provide a pluggable Browserify transform

### ISSUE THREAD

**Issue by benjamn** [facebook/regenerator#20]
As suggested on Hacker News by shtylman:
https://news.ycombinator.com/item?id=6594727

**Comment by zanona** [comment]
I am not sure if this is something that should be held within regenerator but at the moment it seems it's not possible to handle errors emitted through a regenerator transformation through browserify.

So:
```js
browserify(src)
   .transform(require('regenerator'))
   .bundle()
   .on('error', handleError)
   .on('bundle', handleBundle);
```
where `handleError` never gets triggered and the application crashes beforehand because apparently regenerator is throwing an Error instead of emitting through `this.emit('error', new Error())`

more on how to achieve this: 
https://github.com/substack/node-browserify/blob/071642ad9cbb44cb530d43edfac17c5077a9442c/test/tr_error.js#L11-L13
