### ISSUE TITLE
async compiled has unnecessary code

### ISSUE THREAD

**Issue by welefen** [facebook/regenerator#211]
source code:
```
var fn = async function(){
  var data = await Promise.resolve(1);
}
```

compiled code:
```
"use strict";

var _regeneratorRuntime = require("babel-runtime/regenerator")["default"];

var _Promise = require("babel-runtime/core-js/promise")["default"];

var fn = function fn() {
  var data;
  return _regeneratorRuntime.async(function fn$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        context$1$0.next = 2;
        return _regeneratorRuntime.awrap(_Promise.resolve(1));

      case 2:
        data = context$1$0.sent;

      case 3:
      case "end":
        return context$1$0.stop();
    }
  }, null, this);
};

```

code `case 3:` is unnecessary.

**Comment by benjamn** [comment]
That's intentional, because the runtime needs a way to say "jump to the end of the function" without knowing what the numerical offset is, and generated code needs to be able to jump to the numerical offset that happens to fall just after the last statement, before it knows what the last statement will be. These are two different ways of addressing the same location, and both ways are useful. You don't see `context$1$0.next = "end"` anywhere in this generated code, but that doesn't mean it's unused. If the `await` throws an exception because the `Promise` was rejected, that exception will need to thrown into the generator function, which requires the runtime to set `context$1$0.next` behind the scenes. See [here](https://github.com/facebook/regenerator/blob/b3b1222ec1cb22c3ea74c47a1015dcb8408ca6c2/runtime.js#L512) for an example of where that kind of thing happens.

There are lots of opportunities for dead code elimination for generated code, but I believe that's a job best left to a dedicated tool, such as a minifier.
