### ISSUE TITLE
Nested functions can't be properly rebound

### ISSUE THREAD

**Issue by RReverser** [facebook/regenerator#225]
The following code does not transform as expected:

``` js
function parent1() {
  function toBeRebound() {
    toBeRebound = 42;
  }
  toBeRebound();
  console.log(toBeRebound);
}

parent1(); // 42

function *parent2() {
  function toBeRebound() {
    toBeRebound = 42;
  }
  toBeRebound();
  console.log(toBeRebound);
}

parent2().next(); // function toBeRebound() { ... }
```

Functions that are nested in generators are transformed into `originalName = function originalName() { ... }` function expressions. In this case, function name can't be rebound from the inside of the function as such identifiers are bound to function expression and not to variable.

**Comment by benjamn** [comment]
At the very least, it seems like we should be anonymizing `FunctionDeclaration`s that get turned into `AssignmentExpression`s with `FunctionExpression` right-hand sides. So `originalName = function () { ... }` instead of `originalName = function originalName() { ... }`. I believe that's consistent with the way `FunctionDeclaration`s work, if we ignore any problems related to hoisting for now.

**Comment by RReverser** [comment]
Yup, either anynymising or renaming with some suffix as we do when wrapping generator itself.

**Comment by benjamn** [comment]
And just to be clear, I believe (simulated) hoisting [does work](https://github.com/facebook/regenerator/blob/a0fb45fe4060ea93dec7cb93e664114e4e2cdacf/lib/hoist.js#L103-L117).

**Comment by RReverser** [comment]
Sure, did I argue with that?)

**Comment by benjamn** [comment]
Nah, I just wanted to qualify my own suggestion that hoisting might be a problem, because I'm not actually that worried about it :)

**Comment by bsuh** [comment]
Since `@babel/plugin-transform-async-to-generator@7.0.0-beta.35` makes use of rebinding functions (https://github.com/babel/babel/pull/6984). The output of nested asynchronous functions from that transform fed into `@babel/plugin-transform-regenerator` will result in call stack overflow. More details here https://github.com/babel/babel/issues/7134
