### ISSUE TITLE
unknown Statement of type "ForOfStatement"

### ISSUE THREAD

**Issue by jney** [facebook/regenerator#229]
Having a `for .. of` loop in a generator function raise the error : 
```
Error: path/to/file.js: unknown Statement of type "ForOfStatement"
    at Emitter.Ep.explodeStatement (/path/to/project/node_modules/babel-plugin-transform-regenerator/lib/emit.js:648:13)
```

other `for .. of` loops compile as expected

babel-plugin-transform-regenerator version : 6.3.26
babel version : 6.3.26
node version : v5.3.0

**Comment by benjamn** [comment]
Regenerator assumes `for`-`of` loops have been transpiled before it runs, hence the dependency on [`babel-plugin-transform-es2015-for-of`](https://github.com/babel/babel/blob/1ec3a348d628e9a3ac15a6e23423c4329cb55633/packages/babel-plugin-transform-regenerator/package.json#L11).

To be honest, I can't tell where that `babel-plugin-transform-es2015-for-of` gets registered as a prerequisite for `babel-plugin-transform-regenerator`, though. Perhaps the order of the transforms has gotten reversed somehow?

cc @sebmck @amasad

**Comment by jney** [comment]
my bad, i wasn't aware of new plugin architecture

**Comment by jney** [comment]
actually using preset `es2015` or even explicitly calling `transform-regenerator` and 'transform-es2015-for-of' still fail

```
{
  "plugins": ["transform-regenerator" , "transform-es2015-for-of"],
  "presets": ["es2015"]
}
```

**Comment by jney** [comment]
test.js : 

```javascript
'use strict'

class Test {
  * sortedKeys(obj) {
    const keys =
      Object.keys(obj).sort((a, b) => (a > b) ? 1 : ((b > a) ? -1 : 0))
    for (let i in keys) {
      const key = keys[i]
      yield [key, obj[key]]
    }
  }
}

new Test()
```

```
$ ./node_modules/.bin/babel test.js --out-dir dist
test.js -> dist/test.js

$ node dist/test.js
/path/to/dist/test.js:14
    value: regeneratorRuntime.mark(function sortedKeys(obj) {
           ^

ReferenceError: regeneratorRuntime is not defined
    at /path/to/dist/test.js:14:12
    at Object.<anonymous> (/path/to/dist/test.js:55:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by jney** [comment]
adding `transform-runtime` fixed the issue

```
{
  "presets": ["es2015"],
  "plugins": ["transform-runtime"]
}
```

**Comment by benjamn** [comment]
That looks like a bug in the code that detects whether `regeneratorRuntime` is needed, perhaps because that code doesn't consider generator methods, or maybe because something is wrong with the order of imports relative to that `regeneratorRuntime.mark` call. If so, that's probably a Babel bug, better filed [here](https://phabricator.babeljs.io/).

Can you paste the generated code, anyway? I'm away from my computer right now, or I would try it myself.

**Comment by benjamn** [comment]
Oh ok! Might still be a Babel bug, but `transform-runtime` is definitely the way to go.

**Comment by wmertens** [comment]
@benjamn is this still relevant? I am encountering this error when using `for..of` in an async function transpiled with the `babel-preset-env` set to `target: {node: "current"}`. The reason is that Node supports `for..of` natively and thus it does not get transpiled.

Should `regenerator` just ignore `ForOfStatement` or will that break things?
