### ISSUE TITLE
Expose an original source code of the generator function with .toString method

### ISSUE THREAD

**Issue by ayatkevich** [facebook/regenerator#266]
Hi there,

First of all, thank you for the great library!

I'm working on the testing solution for `redux-saga`. And I thought that it would be great if I could provide an enhanced error reporting like:
```js
function * () {
  yield take('log');
  yield call(console.log);
  ^ Expected something like:
    yield call(console.log, "text");
}
```
Although I can do this with the latest v8, I can't with babel, unfortunately.

Right now the code
```js
(function * () {}).toString()
```
returns something like this:
```js
function _callee() {
  return _index2.default.wrap(function _callee$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
        case 'end':
          return _context.stop();
      }
    }
  }, _callee, this);
}
```

Is there any way to expose the original source code of the generator function? I'm not asking to overload toString, I would be happy with toSource function or whatever else.

Thanks!

**Comment by benjamn** [comment]
I understand where you're coming from, but this seems like a feature that should be provided by Babel itself, rather than by individual transforms, since there are likely to be other bits of transformed syntax in the function that aren't specific to generators.

I definitely think it's important that `Function.prototype.toString` returns the code that is actually executing, even if it's been transformed, so I agree that the functionality you're asking for should be provided through some additional API.

Implementation-wise, preserving the original source might be possible if source maps are available, but I'm afraid it doesn't make sense always to ship source maps to the browser to support a special use case like this.

Related tradeoff: Babel *could* fully support `eval`… if a copy of Babel was shipped down to the client along with the compiled program, but no one wants to incur that much overhead to support a better `eval`. There's almost always a cheaper way to accomplish what you want.

**Comment by ayatkevich** [comment]
Thanks, @benjamn! Though, I've just woken up thinking that the best way to provide such error reporting is to deliver my own babel transformer. I'll try go this way.
