### ISSUE TITLE
Is this library still maintained? Or at the very least, "API done"?

### ISSUE THREAD

**Issue by Pomax** [facebook/regenerator#384]
It's currently still a 0.x version, which means that it does not make any promises about some future release not completely breaking anything and everything people might rely on (with 21 million downloads per week, it's fair to see a _lot_ of people rely on this code).

Can this be released as a 1.0.0 at least, so that people can safely add this as project dependency knowing that changes in minor/patch number follow semver?

**Comment by benjamn** [comment]
This project is definitely still maintained, by folks like @nicolo-ribaudo and the Babel team and me, but I think it's worth keeping in mind that the last JS environment without native support for generator functions at this point is IE11, so we (the JS community) are thankfully on the verge of no longer needing this library. Ever since I started working on this project, I dreamed of the day it would become obsolete, and six years later that dream is finally almost about to come true!

The priority is to fix bugs, but otherwise not to make any further investments in new functionality. The library is not perfect, so I do not feel like a 1.0 release would be meaningful, but it has served its purpose well, and anyone still compiling for IE11 should consider building a modern bundle for the other 95%+ of browsers. This is something that [Meteor 1.7](https://www.youtube.com/watch?v=vpCotlPieIY) does automatically, and I hope that other frameworks will follow.

Technically speaking, since most people use the `^` syntax for version constraints in their `package.json` files, a `^0.y.z` version is actually safer than an `^x.y.z` (`x` > 0) version, since `^x.y.z` matches any version greater than `x.y.z` where `x` is the same, whereas `^0.y.z` constrains the `y` version. See [this documentation](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1) about the difference between `~` and `^` syntax.
